//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//

// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string categoria { get; set; }
        public Nullable<int> edadMin { get; set; }
        public Nullable<int> edadMax { get; set; }
        public string tipo { get; set; }
        public string ubicacion { get; set; }
        public string administrador { get; set; }
        public string cupos { get; set; }
    }
}
